PUT http://localhost:8080/api/donation/8
Content-Type: application/json

{
  "quantity": 2,
  "categories": [
    {
      "id": 1,
      "name": "ubrania, które nadają się do ponownego użycia"
    }
  ],
  "institution": {
    "id": 2,
    "name": "A kogo?",
    "description": "Pomoc w wybudzaniu dzieci ze śpiączki"
  },
  "streetName": "testowyJSON street",
  "city": "testowyJSON city",
  "zipCode": "99-999",
  "phoneNumber": "99 9999 999 ",
  "pickUpDate": "2000-01-01",
  "pickUpTime": "01:01:01",
  "comment": "No Comment dla testowego JSONA"
}